// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef AGH_SOCFPGA_H
#define AGH_SOCFPGA_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

// Reg - csr.IO_CR
#define CSR__IO_CR__VAL_bm 0xff
#define CSR__IO_CR__VAL_bp 0
#define CSR__IO_CR__VAL_bw 8
#define CSR__IO_CR__VAL_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t val :8;
        uint32_t :24;
    } f;
    uint32_t w;
} csr__IO_CR_t;

// Reg - csr.SCRATCHPAD
#define CSR__SCRATCHPAD__VAL_bm 0xffffffff
#define CSR__SCRATCHPAD__VAL_bp 0
#define CSR__SCRATCHPAD__VAL_bw 32
#define CSR__SCRATCHPAD__VAL_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint32_t val :32;
    } f;
    uint32_t w;
} csr__SCRATCHPAD_t;

// Addrmap - csr
typedef struct __attribute__ ((__packed__)) {
    csr__IO_CR_t IO_CR;
    uint8_t RESERVED_4_3fb[0x3f8];
    csr__SCRATCHPAD_t SCRATCHPAD;
} csr_t;


static_assert(sizeof(csr_t) == 0x400, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* AGH_SOCFPGA_H */
