# TCL File Generated by Component Editor 23.1
# Wed Jun 05 11:47:20 CEST 2024
# DO NOT MODIFY


# 
# agh_socfpga "agh_socfpga" v1.0
#  2024.06.05.11:47:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module agh_socfpga
# 
set_module_property DESCRIPTION ""
set_module_property NAME agh_socfpga
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME agh_socfpga
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL agh_socfpga
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file csr.sv SYSTEM_VERILOG PATH ../rtl/agh_socfpga/csr.sv
add_fileset_file csr_pkg.sv SYSTEM_VERILOG PATH ../rtl/agh_socfpga/csr_pkg.sv
add_fileset_file agh_socfpga.sv SYSTEM_VERILOG PATH ../rtl/agh_socfpga/agh_socfpga.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point io
# 
add_interface io conduit end
set_interface_property io associatedClock clock
set_interface_property io associatedReset ""
set_interface_property io ENABLED true
set_interface_property io EXPORT_OF ""
set_interface_property io PORT_NAME_MAP ""
set_interface_property io CMSIS_SVD_VARIABLES ""
set_interface_property io SVD_ADDRESS_GROUP ""

add_interface_port io led led Output 8


# 
# connection point avalon_mm_slave
# 
add_interface avalon_mm_slave avalon end
set_interface_property avalon_mm_slave addressUnits WORDS
set_interface_property avalon_mm_slave associatedClock clock
set_interface_property avalon_mm_slave associatedReset reset
set_interface_property avalon_mm_slave bitsPerSymbol 8
set_interface_property avalon_mm_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_mm_slave burstcountUnits WORDS
set_interface_property avalon_mm_slave explicitAddressSpan 0
set_interface_property avalon_mm_slave holdTime 0
set_interface_property avalon_mm_slave linewrapBursts false
set_interface_property avalon_mm_slave maximumPendingReadTransactions 1
set_interface_property avalon_mm_slave maximumPendingWriteTransactions 1
set_interface_property avalon_mm_slave readLatency 0
set_interface_property avalon_mm_slave readWaitTime 1
set_interface_property avalon_mm_slave setupTime 0
set_interface_property avalon_mm_slave timingUnits Cycles
set_interface_property avalon_mm_slave writeWaitTime 0
set_interface_property avalon_mm_slave ENABLED true
set_interface_property avalon_mm_slave EXPORT_OF ""
set_interface_property avalon_mm_slave PORT_NAME_MAP ""
set_interface_property avalon_mm_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_mm_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_mm_slave avalon_mm_slave_waitrequest waitrequest Output 1
add_interface_port avalon_mm_slave avalon_mm_slave_response response Output 2
add_interface_port avalon_mm_slave avalon_mm_slave_readdatavalid readdatavalid Output 1
add_interface_port avalon_mm_slave avalon_mm_slave_writeresponsevalid writeresponsevalid Output 1
add_interface_port avalon_mm_slave avalon_mm_slave_readdata readdata Output 32
add_interface_port avalon_mm_slave avalon_mm_slave_address address Input 12
add_interface_port avalon_mm_slave avalon_mm_slave_read read Input 1
add_interface_port avalon_mm_slave avalon_mm_slave_write write Input 1
add_interface_port avalon_mm_slave avalon_mm_slave_byteenable byteenable Input 4
add_interface_port avalon_mm_slave avalon_mm_slave_writedata writedata Input 32
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_mm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source avalon_streaming_source_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source avalon_streaming_source_data data Output 16
add_interface_port avalon_streaming_source avalon_streaming_source_ready ready Input 1
add_interface_port avalon_streaming_source avalon_streaming_source_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source avalon_streaming_source_valid valid Output 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink avalon_streaming_sink_data data Input 16
add_interface_port avalon_streaming_sink avalon_streaming_sink_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink avalon_streaming_sink_valid valid Input 1
add_interface_port avalon_streaming_sink avalon_streaming_sink_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink avalon_streaming_sink_ready ready Output 1

