// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package csr_pkg;

    localparam CSR_DATA_WIDTH = 32;
    localparam CSR_MIN_ADDR_WIDTH = 12;

    typedef struct {
        logic hwset;
    } csr__TEST_REG__val__in_t;

    typedef struct {
        csr__TEST_REG__val__in_t val;
    } csr__TEST_REG__in_t;

    typedef struct {
        csr__TEST_REG__in_t TEST_REG;
    } csr__in_t;

    typedef struct {
        logic [7:0] value;
    } csr__IO_CR__val__out_t;

    typedef struct {
        csr__IO_CR__val__out_t val;
    } csr__IO_CR__out_t;

    typedef struct {
        csr__IO_CR__out_t IO_CR;
    } csr__out_t;
endpackage
